name: Push to Replicate

on:
  push:
    branches:
      - main
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push model to Replicate
        run: cog push r8.im/zakiibnu723/ageme-face-aging
